name: ACL指纹更新

on:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: n1
      run: curl -s https://install.zerotier.com | sudo bash
    - name: n2
      run: sudo ufw allow 9993/udp
    - name: n3
      run: sudo ufw reload
    - name: n4
      run: sudo systemctl start zerotier-one
    - name: n5
      run: sudo systemctl enable zerotier-one
    - name: n6
      run: sudo systemctl enable systemd-networkd-wait-online
    - name: n7
      run: sudo zerotier-cli join  ${{ secrets.Network_ID}}
    - name: 获取授权id
      run: sudo zerotier-cli status
    - name: n9
      run: sudo zerotier-cli peers
    - name: n9
      run: sleep 2m
    - name: 下载凌洞指纹
      run: wget -P /tmp https://raw.githubusercontent.com/EdgeSecurityTeam/EHole/main/finger.json && wget -P /tmp https://raw.githubusercontent.com/loecho-sec/ARL-Finger-ADD/main/ARL-Finger-ADD.py
    - name: 更新凌洞指纹
      run: cd /tmp &&sudo python /tmp/ARL-Finger-ADD.py https://10.147.19.214:5003/ ${{ secrets.userName}} ${{ secrets.Password}}
