name: List Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: List files
      run: wget https://github.com/fatedier/frp/releases/download/v0.51.0/frp_0.51.0_linux_amd64.tar.gz && tar -zxvf frp_0.51.0_linux_amd64.tar.gz&&cd frp_0.51.0_linux_amd64 &&ls -al
