name: List123

on:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
    - name: n1
      run: |
        sudo docker pull teddysun/v2ray
        sudo mkdir -p /etc/v2ray
        cd /etc/v2ray
        sudo touch config.json
        sudo chmod 777 /etc/v2ray/config.json
        sudo ls -al
        sudo pwd
        cat > config.json << EOD
          {
            "log": {
              "loglevel": "info"
            },
            "inbounds": [
              {
                "port": 3456,
                "protocol": "vmess",
                "allocate": {
                  "strategy": "always"
                },
                "settings": {
                  "clients": [
                    {
                      "id": "26e3a620-e33e-45e6-b316-4570b0ecf39c",
                      "level": 1,
                      "alterId": 0,
                      "email": "client@example.com"
                    }
                  ],
                  "disableInsecureEncryption": true
                },
                "streamSettings": {
                  "network": "ws",
                  "wsSettings": {
                    "connectionReuse": true,
                    "path": "/graphql"
                  },
                  "security": "none",
                  "tcpSettings": {
                    "header": {
                      "type": "http",
                      "response": {
                        "version": "1.1",
                        "status": "200",
                        "reason": "OK",
                        "headers": {
                          "Content-Type": [
                            "application/octet-stream",
                            "application/x-msdownload",
                            "text/html",
                            "application/x-shockwave-flash"
                          ],
                          "Transfer-Encoding": ["chunked"],
                          "Connection": ["keep-alive"],
                          "Pragma": "no-cache"
                        }
                      }
                    }
                  }
                }
              }
            ],
            "outbounds": [
              {
                "protocol": "freedom",
                "settings": {}
              },
              {
                "protocol": "blackhole",
                "settings": {},
                "tag": "blocked"
              }
            ],
            "routing": {
              "domainStrategy": "AsIs",
              "rules": [
                {
                  "type": "field",
                  "ip": [
                    "0.0.0.0/8",
                    "10.0.0.0/8",
                    "100.64.0.0/10",
                    "127.0.0.0/8",
                    "169.254.0.0/16",
                    "172.16.0.0/12",
                    "192.0.0.0/24",
                    "192.0.2.0/24",
                    "192.168.0.0/16",
                    "198.18.0.0/15",
                    "198.51.100.0/24",
                    "203.0.113.0/24",
                    "::1/128",
                    "fc00::/7",
                    "fe80::/10",
                    "geoip:private"
                  ],
                  "outboundTag": "blocked"
                },
                {
                  "type": "field",
                  "protocol": ["bittorrent"],
                  "outboundTag": "blocked"
                }
              ]
            }
          }
          EOD
        sudo docker run -d -p 9000:9000 --name v2ray --restart=always -v /etc/v2ray:/etc/v2ray teddysun/v2ray
